### PR TITLE
[FIX] Some code fixes.

### PR DESCRIPTION
**Pull request by Anderson-SG**
In order to follow good practices, make the code more readable and friendly to contributors and even improve performance in some cases, I made some changes to the code in order to improve the quality of the application.

it was really simple things like removing useless "this", using the new await convention in using, a few null validations, redundant initializers and a few other simple things.

No big brain code here.

### CODE REVIEW

**Comment by Seb-stian** [comment]
I see that you've removed extra `this.`es 😄
@Tides

**Comment by Tides** [comment]
> I see that you've removed extra `this.`es 😄 @Tides

pain

**Comment by Naamloos** [comment]
The opinions on thises are mixed 😅 I'll review later today if it's not merged yet

**Comment by Jonpro03** [comment]
I'm surprised @Tides didn't just outright reject the PR 😆

**Comment by Tides** [comment]
> I'm surprised @Tides didn't just outright reject the PR 😆

I haven't got to look at it yet 👀

**Comment by Jonpro03** [comment]
@Anderson-SG we were reviewing this PR if you'd like to reopen. We're just giving each other a hard time for not following convention

**Pull request closed without merging**
