### PR TITLE
Add global usings

### LINKED ISSUE #186: Add global usings
I suggest adding `global using`s for the following:
- `System`
- `System.Linq`
- `System.Collections.Generic`
- `static` `Obsidian.Utilities.Extensions`

Other candidates:
- `System.Collections.Concurrent`
- `System.Threading.Tasks`
- `Obsidian.API`

### PR DESCRIPTION
**Pull request by Seb-stian**
Closes #186

### CODE REVIEW

**Comment by Seb-stian** [comment]
Add [GlobalUsings.cs](https://github.com/ObsidianMC/Obsidian/pull/187/files#diff-bb30b219d7d44c459e17280b47c3822ddca8fb27d4004cb3316ce4dbf79cfcfd) and removed redundant usings from the project.

**Review by Naamloos — APPROVED** [review]
Clean. nice.

**Comment by Seb-stian** [comment]
Should I take the same approach for all projects (besides `Obsidian.API`, that won't reference itself)?

**Comment by Seb-stian** [comment]
Relevant changes:
[Obsidian](https://github.com/ObsidianMC/Obsidian/pull/187/files#diff-bb30b219d7d44c459e17280b47c3822ddca8fb27d4004cb3316ce4dbf79cfcfd)
[Obsidian.API](https://github.com/ObsidianMC/Obsidian/pull/187/files#diff-27c63db79329f43516b750563ba2161ce34ebc82a1d2f2cba148048783a42e8b)
[Obsidian.Nbt](https://github.com/ObsidianMC/Obsidian/pull/187/files#diff-e6b9e6334cabde5d2c750fc74cd3b36f54f75c999ef10554fc6b925e7ed36961)
[Obsidian.SourceGenerators](https://github.com/ObsidianMC/Obsidian/pull/187/files#diff-f86c76d0e1635881a8df9804182a01620b0fc01f92ceb01a4d39db07a28b274e)

**Review by Naamloos — APPROVED** [review]
Still don't see anything weird.

**Pull request merged**
