### PR TITLE
And then naamloos said... let there be light! (but really mojang really just handles it for us lol)

### PR DESCRIPTION
**Pull request by Naamloos**
yeah.. client seems to be OK with grabage data and decides to handle light itself. Not sending data seems not to be an option though..

### CODE REVIEW

**Review by Craftplacer — APPROVED** [review]
LGTM like always Naam Naam

**Comment by Naamloos** [comment]
The PR is broken. don't merge yet.

**Comment by Seb-stian** [comment]
From discord:
> Naamloos: turns out the mod ignores light data and not vanilla

Is this PR dead then? 💀

**Comment by Naamloos** [comment]
The light lacket is still implemented. Is it possible to cherry pick changes?

**Comment by Naamloos** [comment]
The hardcoded values need to be removed / fixed

**Comment by Seb-stian** [comment]
Copy-paste (with changes) to feature/packets and close this? I volunteer

**Comment by Seb-stian** [comment]
Done → https://github.com/ObsidianMC/Obsidian/commit/2aa51e36c883843ff039b15597b3c644b883b533

**Comment by Naamloos** [comment]
👌 Closing

**Pull request closed without merging**
