### PR TITLE
Minor changes and additions

### PR DESCRIPTION
**Pull request by VoOoLoX**

### CODE REVIEW

**Review by Craftplacer — APPROVED** [review]
The commands.json is not needed and probably won't because we don't have any plans to port the vanilla command system and its commands.

Ignoring that, everything seems fine.

**Comment by VoOoLoX** [comment]
Great I was wondering if I should include commands.json or not, guess I'll remove it.
I think it would be nice to have a tool to extract blocks and items files from the actual jar as a separate project maybe or at least guide in the README because it took me some time to figure it out. Anyway I might look into it later.

**Comment by Naamloos** [comment]
@Tides updates on review?

**Comment by Craftplacer** [comment]
> @Tides updates on review?

bump

**Review by Tides — APPROVED** [review]
Sorry for the late response but all changes seem fine to me 😃

**Pull request merged**
