### PR TITLE
Make /time command behave like vanilla

### PR DESCRIPTION
**Pull request by ghost**
I am not sure how to implement `/time` command without arguments and `/time query` command which also takes no arguments.
What have been implemented:
- set command
- add command
 
https://github.com/ObsidianMC/Obsidian/issues/282
In the issue world's total time is a different task, doesn't depend on the /time command. The overflow is also done separately, commands do not handle that in Obsidian as I understand, they just get values in arguments, if it's overflowing they get nothing.

### CODE REVIEW

**Comment by abzh423** [comment]
Okay, I kinda got bored with minecraft. It sugs, will retrieve for a while.

**Comment by abzh423** [comment]
If you don't need this pull requests, just close it

**Comment by ghost** [comment]
Tagged: @Naamloos @Tides @Craftplacer @Seb-stian @Jonpro03 
Can someone at least give some feedback guys? I will fix the code if needed.

**Comment by Tides** [comment]
Hey, I see you're using parameters instead of creating a sub command. I would recommend staying away from this until we re-implement a fixed command api/system~

**Comment by ghost** [comment]
> Hey, I see you're using parameters instead of creating a sub command. I would recommend staying away from this until we re-implement a fixed command api/system~

Ok, any suggestions on what should I work?

**Pull request closed without merging**
