### PR TITLE
Move Configs and Worlds into Subfolders and clean some Stuff up

### PR DESCRIPTION
**Pull request by Aaron2550**
Tested, everything seems to work just like before my changes. Worlds and Configs generate and load fine and sub-folders get created if they don't exist.

I deleted a line in Obsidian.ConsoleApp/Program.cs that was useless, idk what was up with that.
I deleted the .editorconfig in Obsidian.ConsoleApp, see [this](https://discord.com/channels/772894170451804220/772894226756403251/1003792520163115040) for reasoning

No Idea what we are gonna do about the editorconfig tho, i couldnt disable or exclude it from the commit and VS put some stuff in there + german comments, want me to try and re-do the commit or do we just accept that and ignore it?

### CODE REVIEW

**Comment by Aaron2550** [comment]
I can't really test the last commit, which changes the Permissions Folder Path since no Files get created in that Folder but since it's just a rename it should™ be fine

**Comment by Tides** [comment]
Everything looks good except the capitalized folders and file names, if you can change those to be lowercase I'll approve 👍🏼

**Comment by Seb-stian** [comment]
> Everything looks good except the capitalized folders and file names, if you can change those to be lowercase I'll approve 👍🏼

Same here, although I'm open to discussion

**Comment by Naamloos** [comment]
What's the new structure?

**Comment by Aaron2550** [comment]
the same but with lowercase folder name

**Comment by Naamloos** [comment]
+ I'd personally prefer lowercase folder names by the way.

**Comment by Naamloos** [comment]
I meant for this whole PR

**Comment by Craftplacer** [comment]
lowercase all the way

**Review by Seb-stian — APPROVED** [review]

**Comment by Seb-stian** [comment]
Directories in question are `config`/`Config` and `worlds`/`Worlds`.
After consideration I arrived to the conclusion that the correct naming would be `config` and `worlds`. My reasoning comes from the way C# (and probably .NET) applications conventionally name their directories (and files).

Solution/Project/Source file → PascalCase
other → lowercase

For example, in dotnet/runtime, you can find a path [src](https://github.com/dotnet/runtime/tree/main/src)/[tests](https://github.com/dotnet/runtime/tree/main/src/tests)/[reflection](https://github.com/dotnet/runtime/tree/main/src/tests/reflection)/[GenericAttribute](https://github.com/dotnet/runtime/tree/main/src/tests/reflection/GenericAttribute)/[GenericAttributeTests.csproj](https://github.com/dotnet/runtime/blob/main/src/tests/reflection/GenericAttribute/GenericAttributeTests.csproj)

Neither `config` or `worlds` are project directories and so they should be named in lowercase.

**Comment by Naamloos** [comment]
also, lower case is also more convenient if you're hosting on linux :^)

**Review by Naamloos — APPROVED** [review]
lgtm.

**Pull request merged**
