### PR TITLE
Fix console input blocking server in linux

### LINKED ISSUE #264: Console.ReadKey() blocking the entire server in Linux
While testing the server for the first time on a Linux PC, I found a bug. 

When the console app waits for a keypress, the entire server blocks and doesn't log anything or send any packets to the client until the enter key is pressed (one or multiple times).
image

If no one is against it, I'll make a pull request now with the fix.

<sub>Sorry for my bad English, I'm not a native speaker<sub>

### PR DESCRIPTION
**Pull request by GasInfinity**
Fixes #264

### CODE REVIEW

**Review by Seb-stian — CHANGES_REQUESTED** [review]
Thank you for the PR. I see few problems here. I believe the license on this file requires you to

> include a notice in each of Your Modifications that identifies You as the Contributor of the Modification

Furthermore, although it is (I assume) a working solution, active waiting is not ideal. We can merge it for now (after the licensing issue is solved) and improve it later (let's not forget to open a new issue for it, if we go down that route).

**Review by Seb-stian — APPROVED** [review]

**Comment by GasInfinity** [comment]
> Furthermore, although it is (I assume) a working solution, active waiting is not ideal. We can merge it for now (after the licensing issue is solved) and improve it later (let's not forget to open a new issue for it, if we go down that route).

Yes, active waiting is not ideal. I was thinking about doing a ```Task.Delay()``` but that would introduce some input lag.

Edit: I'm very dumb, that isn't an async function

**Comment by Seb-stian** [comment]
Can you confirm that this actually works? Did you test it?

**Comment by GasInfinity** [comment]
Yes, I'm actually connected to my local server now and it works. Now before this gets merged I want to resolve the empty while loop, i think that a simple `Thread.Sleep()` would work but as I've said before that could introduce some input lag.

**Comment by Craftplacer** [comment]
Does the bug appear without this PR? Polling for an available key is an odd solution to me.

**Comment by Seb-stian** [comment]
@Craftplacer 
> Does the bug appear without this PR?

This is a known bug that has been reported by different users before.

**Comment by GasInfinity** [comment]
> Does the bug appear without this PR? Polling for an available key is an odd solution to me.

Yes, without this PR, the server is practically unusable in Linux (at least on my PC).

There are other solutions like enabling BasicIO, but you loose some useful features.

I can't test this PR in Windows right now, but I think it should work fine there.

**Comment by Craftplacer** [comment]
I don't understand why this fix is necessary in the first place (why doesn't ReadKey work under Linux?), is this a framework bug?

**Comment by GasInfinity** [comment]
> I don't understand why this fix is necessary in the first place (why doesn't ReadKey work under Linux?), is this a framework bug?

I think this could be related:
https://github.com/dotnet/runtime/issues/34239

Edit: I'm 90% sure that that's the problem.

**Comment by Jonpro03** [comment]
> > I don't understand why this fix is necessary in the first place (why doesn't ReadKey work under Linux?), is this a framework bug?
> 
> I think this could be related: [dotnet/runtime#34239](https://github.com/dotnet/runtime/issues/34239)
> 
> Edit: I'm 90% sure that that's the problem.

Thank you for finding that. 
It was driving me nuts not knowing why linux was broken.

**Review by Jonpro03 — APPROVED** [review]

**Comment by Naamloos** [comment]
Personally I think it's best to ignore console input altogether now that rcon is coming...

**Comment by Craftplacer** [comment]
> > I don't understand why this fix is necessary in the first place (why doesn't ReadKey work under Linux?), is this a framework bug?
> 
> I think this could be related: [dotnet/runtime#34239](https://github.com/dotnet/runtime/issues/34239)
> 
> Edit: I'm 90% sure that that's the problem.

We should redo this then and come up with this design:

Thread 1: Dequeues WriteLine's and handles console I/O
Thread 2, 3, ...: Queue WriteLines to the host console

This design should only apply to the host console I think, unnecessary for other ones

**Comment by GasInfinity** [comment]
> > > I don't understand why this fix is necessary in the first place (why doesn't ReadKey work under Linux?), is this a framework bug?
> > 
> > I think this could be related: [dotnet/runtime#34239](https://github.com/dotnet/runtime/issues/34239)
> > 
> > Edit: I'm 90% sure that that's the problem.
> 
> We should redo this then and come up with this design:
> 
> Thread 1: Dequeues WriteLine's and handles console I/O
> Thread 2, 3, ...: Queue WriteLines to the host console
> 
> This design should only apply to the host console I think, unnecessary for other ones

That should work, the other threads won't block.

But if we want a fancy status line and some other features we would still need to check for `Console.KeyAvailable`, because those WriteLines would need to wait for a key to be written on the Console.

But I think that it would be better to open other PR later to redo that.

**Comment by Craftplacer** [comment]
I would recommend to wrap the while statement with a platform check (this is Linux only apparently) so we can finally merge this fix.

**Pull request merged**
