### PR TITLE
Add Block to API

### PR DESCRIPTION
**Pull request by Seb-stian**

### CODE REVIEW

**Comment by Seb-stian** [comment]
Issues to solve:
- [x] Cancelling the `BlockBreak` event doesn't prevent breaking the block client-side
- [x] `IWorld.SetBlock` doesn't send `BlockChange` to clients

**Review by Jonpro03 — APPROVED** [review]

**Comment by Seb-stian** [comment]
Some significant changes were made. World now has `SetBlock` that sends `BlockChange` to players and `SetBlockUntracked` that doesn't. Block was moved to `Obsidian.API`. Server has a synchronous block placement broadcast method (this may count as a workaround 😬).

**Review by Naamloos — APPROVED** [review]
All in all looks fine to me. Nice job.

**Comment by Tides** [comment]
👍🏼

**Review by Tides — APPROVED** [review]

**Pull request merged**
