### PR TITLE
Changed 1.15  JSON Syntax to 1.16  JSON Syntax

### PR DESCRIPTION
**Pull request by roxxel**
#### Summary:
- Separated ITextComponent to IHoverComponent and IClickComponent (EClickAction & EHoverAction as well)
- [HoverComponent now uses `Contents`  instead of `Value`](https://github.com/ObsidianMC/Obsidian/commit/b8445be0a151187ced707ba53f647cf080bf65b6#diff-88201f9139dae3c3d7f35bd0a4b8ee34b1d86d7dd7ca814ecdf5f2835c8bec98R13)
- ~~Added OpenFile action because it was missing~~
- Small [visual improvement](https://github.com/ObsidianMC/Obsidian/commit/b8445be0a151187ced707ba53f647cf080bf65b6#diff-9198876d9125942e839dcfb44d58bac0e9ffa228d3877fb1cb485182132e5758R158) in MainCommandModule

### CODE REVIEW

**Comment by Naamloos** [comment]
LGTM

**Comment by Seb-stian** [comment]
[Wiki page](https://github.com/ObsidianMC/Obsidian/wiki/Chat-messages) will need to be updated after merge.

**Comment by Naamloos** [comment]
We have a wiki? xD

**Comment by Craftplacer** [comment]
> We have a wiki? xD

We have a wiki?

**Review by Craftplacer — APPROVED** [review]
lgtm

**Comment by Naamloos** [comment]
Enough approval, merging.

**Pull request merged**
