### PR TITLE
Improve counting non-air blocks performance

### PR DESCRIPTION
**Pull request by Seb-stian**

### CODE REVIEW

**Comment by Naamloos** [comment]
Seems fine to me tbh

**Comment by Seb-stian** [comment]
CPU profiling showed a solid improvement. I playtested my changes and everything works fine. But the changes are breaking, and so I would like @Tides to inspect them first 👀 (as he is working on the branch intensely).

**Comment by Naamloos** [comment]
makes sense :)

**Review by Tides — APPROVED** [review]
LGTM 👍🏼 I like the TryGet/GetOrAddId methods

**Pull request merged**
